### ISSUE TITLE
ENOENT; missing serverPath

### ISSUE THREAD

**Issue by idelfonsog2** [pwsacademy/swift-setup#3]
```markdown
ENOENT: no such file or directory, stat 'sourcekit-lsp.serverPath'
```

editor: VSCode

I'm getting the above warning. In my project VsCode has requested me to create two files in order to debug my vapor application in it, which look like the following:

```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceFolder}/TILApp",
            "args": [],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "swift build",
            "type": "shell",
            "command": "swift build",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

The SourceKitLSP settings look like the following:

- Server Path: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp
- Toolchain Path: 

Any suggestions?

**Comment by svanimpe** [comment]
I haven't tried macOS yet (that's why it's not listed among the supported platforms for Visual Studio Code), but my first guess is that maybe you don't need to set the server path and toolchain path any more.

On Linux and Windows, SourceKit-LSP works just fine without any settings, as long as `swift` and `sourcekit-lsp` are on the PATH.

**Comment by svanimpe** [comment]
Also, see the instructions for VS Code for a correct `launch.json` configuration. I assume your `program` setting is incorrect and that you're missing a `preLaunchTask` setting?

**Comment by idelfonsog2** [comment]
> I did a quick check, and it turns out that `sourcekit-lsp` isn't on the PATH on macOS. However, the following setting does work fine for me:
> 
> ```
> "sourcekit-lsp.serverPath": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp",
> ```
> 
> Did you verify this file exists?
> That is, I assume you have Xcode installed, as well as its command line tools?

Thank you for the quick response @svanimpe ! 

I added to my $PATH: ` /Users/idelfonso/anaconda3/bin:/Users/idelfonso/anaconda3/condabin:/Users/idelfonso/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin`

Also I do have Xcode install and I found the path as the one mention abode with the following:

```sh
> xcrun --find sourcekit-lsp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp
```

I'll check the instructions on that file Thanks!

**Comment by idelfonsog2** [comment]
oh wait its actually not there!

**Comment by svanimpe** [comment]
So it's fixed now?

**Comment by idelfonsog2** [comment]
Apologize, I am still seeing that I might not have followed the instructions properly. For the LLDB library to specify in VSCode editor for macOS, would it be where it is?

`xcrun --find lldb`
`/Applications/Xcode.app/Contents/Developer/usr/bin/lldb`

![Screen Shot 2020-11-03 at 08 16 06](https://user-images.githubusercontent.com/7195235/97996325-37f0ae80-1dad-11eb-9971-af0a77186663.png)

**Comment by svanimpe** [comment]
This works for me: **/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/LLDB**

For **launch.json** and **tasks.json** I used the same values as on Linux.

**Comment by idelfonsog2** [comment]
Thank you @svanimpe that path worked for me and for the **launch.json** I used the following. In macOS, the executable has a different path and name.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceFolder}/.build/x86_64-apple-macosx/debug/Run",
            "args": [],
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "swift build",
        }
    ]
}
```

**Comment by svanimpe** [comment]
In the instructions, the path is **${workspaceFolder}/.build/debug/\<program\>** where `<program>` is the name of your executable target. In your case, the executable seems to **Run**, so **${workspaceFolder}/.build/debug/Run** should work. 

That **.build/debug** folder is just a symbolic link to a platform-dependent folder (such as **.build/x86_64-apple-macosx/debug**), which is why I prefer it.
